### ISSUE TITLE
Password with single quote '

### ISSUE THREAD

**Issue by plantjes** [NeosIT/active-directory-integration2#20] opened 2016-09-19 13:10 UTC
Hi,

My AD administrator account password contains a single quote ( ' ) . The verifications fails, but not if I place this code in wp-content/plugins/active-directory-integration2/vendor/adLDAP/adLDAP.php (line 443)

`$this->_ad_password = "mypassword"; `

Is this a bug?

**Comment by Tobi823** [comment] 2016-09-19 14:33
Hi plantjes,

I cant reproduce your bug. I reset the password of my user "klammer" to "kla'mmer123" and I was able to login.

Can you add this to classes/Adi/Authentication/LoginService.php Line 143
`var_dump($password);
 var_dump(mb_detect_encoding($password));`

And that to vendor/adLDAP/adLDAP.php Line 488
`var_dump($password);
 var_dump(mb_detect_encoding($password));
 die();`

Please make sure, that you can remove the `die()` after this test. This command will crash the WordPress instance for everyone, who wants to login/logout.

Does the password look different? Do you have something else than ASCII?
Which OS are you using? Which Apache/PHP version? Which language/system encoding?

I think that this problem is related to character encoding but I am not sure.

**Comment by schakko** [comment] 2016-09-19 14:43
@Tobi823 This could be a problem with magic quotes if an old PHP version is used. The single quote could be persisted as "\'".

@plantjes is your password quoted if you output the password in adLDAP.php?

**Comment by plantjes** [comment] 2016-09-19 15:03
@Tobi823 @schakko Thank you for responding. The encoding is ASCII. If I output my password on line 443 the single quote is escaped with a backslash. Like this: "kla\'mmer123"

Server info (vagrant):
- Linux vvv 3.13.0-76-generic #120-Ubuntu x86_64
- PHP Version: 5.5.9-1ubuntu4.17

Do you need more info?

**Comment by Tobi823** [comment] 2016-09-20 07:08
@plantjes 
I could not reproduce this bug yet. Can you:

1. add this code:
`if (isset($_POST['pwd'])) {
		$aaa = $_POST['pwd'];
		var_dump($_POST['pwd']);
	}`
to wp-includes/load.php line 648 before the comment "// Escape with wpdb."?

2. add this code:
`if (isset($_POST['pwd'])) {
		var_dump($_POST['pwd']);
		$bbb = stripslashes($_POST['pwd']);
		var_dump($bbb);
		if ($bbb === $aaa) {
			echo 'stripslashes works';
		} else {
			echo 'stripslashes works NOT';
		}
		die();
	}`

to wp-includes/load.php line 654 after `$_SERVER = add_magic_quotes( $_SERVER );` ?

3. 
- logout in WordPress
- go to the WordPress login page
- open your developer console by pressing F12 (for Firefox and Chrome)
- select Network
- enter your username + password and click on login
- click on the "wp-login.php" entry inside your webdeveloper console
- Firefox: click on Params and verify that pwd contains your correct password
- Chrome: click on Headers, scroll to the bottom to Form Data and verify that pwd contains your correct password

![screenshot from 2016-09-20 09-01-15](https://cloud.githubusercontent.com/assets/10066140/18660597/aa85dd6a-7f11-11e6-9e80-11b4d25edd6b.png)
![screenshot from 2016-09-20 09-03-23](https://cloud.githubusercontent.com/assets/10066140/18660598/ae1693ca-7f11-11e6-8d58-69dd7fcb805c.png)

Can you send me your results?

**Comment by plantjes** [comment] 2016-09-20 07:56
**Hmm, my results:** 
Chrome: string(6) "test't" string(7) "test\'t" string(6) "test't" stripslashes works
Firefox: string(6) "test't" string(7) "test\'t" string(6) "test't" stripslashes works

![image](https://cloud.githubusercontent.com/assets/5704284/18661240/05adda14-7f15-11e6-8ae7-c0ad0837b256.png)
![image](https://cloud.githubusercontent.com/assets/5704284/18661754/a87cae08-7f17-11e6-93c9-b5b87c38eb8f.png)

Maybe I was not clear, but I have the problem in the environment tab (Verify credentials):

![image](https://cloud.githubusercontent.com/assets/5704284/18661941/5ba1fa92-7f18-11e6-9e7c-601b68fdfc41.png)

var_dump($this->_ad_password); line 443 -> adLDAP.php

**Comment by Tobi823** [comment] 2016-09-20 09:21
Hi plantjes,

i found the bug. WordPress escape on every request every element in $_POST, $_GET etc. 

For example you can't exclude the username a'b from authentication because WordPress calls addslashes("a'b") and replace the function return value "a\'b" with the original value "a'b".

I try to fix the bug as soon as possible. But you can fix your problem with the password by replacing 

`$data = $data["data"];` in classes/Multisite/Ui/BlogConfigurationPage.php Line 345 with `$data = stripslashes_deep($data["data"]);` 

and

`$data = $data["data"];` in classes/Multisite/Ui/ProfileConfigurationPage.php Line 236 with `$data = stripslashes_deep($data["data"]);`

**Comment by plantjes** [comment] 2016-09-20 12:00
Hi @Tobi823 ,

Thank you for the workarround!

**Comment by Tobi823** [comment] 2016-09-22 05:52
Hi plantjes,

the bug is fixed in version 2.0.6

**Closed by Tobi823** 2016-09-22 05:52 UTC
Labels: bug
