### ISSUE TITLE
Problems Connecting to AD with SSL

### ISSUE THREAD

**Issue by sksoftwaredev** [NeosIT/active-directory-integration2#85] opened 2018-08-03 17:34 UTC
Environment:
Bitnami WAMP Stack Version 7.1.18-1
Apache Version 2.4.33
PHP 7.2.6
WP Version 4.9.8
NADI Version 2.12
Server: Windows Server 2016
AD Server: Windows Server 2016 (separate machine)

I'm trying to configure NADI to use LDAPs on port 636 but I cannot get it to work.

It connects just fine if I disable encryption and use port 389, so I know the domain controller, base DN, username and password that I'm giving it are correct. For some reason though, it refuses to work on port 636.

My log file gives me this:

`[ERROR] NextADInt_Ldap_Connection::connect [line 61] Creating adLDAP object failed. Bind to Active Directory failed. Either the LDAPs connection failed or the login credentials are incorrect. [AD: Can't contact LDAP server] [AD error code: -1]`

I know it has to be the connection because as I said the login works when I pass it as unencrypted through 389. I'll also mention that trying to use STARTTLS on 389 doesn't work.

Anyone know what the problem might be?

**Comment by MeissnerDa** [comment] 2018-08-06 09:08
Hello @sksoftwaredev ,
did you follow our documentation https://active-directory-wp.com/docs/Networking/Encryption_with_TLS.html ?

Best regards,
MeissnerDa

**Comment by sksoftwaredev** [comment] 2018-08-06 19:36
Yes, I did.

**Comment by sksoftwaredev** [comment] 2018-08-06 20:25
Yes, our domain controller and everything is configured. The only part of the config I wasn't sure about was LDAP and OpenSSL - are those requirements? I assume they are but it was never explicitly said in the documentation that they had to be installed.

**Comment by MeissnerDa** [comment] 2018-08-07 08:39
Hello @sksoftwaredev, 

are you referencing to the PHP modules? For NADI to work properly you need to have the LDAP module and the OpenSSL module enabled. (https://active-directory-wp.com/docs/Getting_Started.html -> Requirements)

Best regards,
meissnerDa

**Comment by sksoftwaredev** [comment] 2018-08-07 12:11
You are referring to the extensions in php.ini, correct? If so, I already have those enabled.

What I'm not sure about is whether or not I need to install separate programs for OpenSSL and OpenLDAP.

Under the section "RETRIEVE DOMAIN CONTROLLER CERTIFICATE" in the documentation about TLS encryption, it says "With OpenSSL installed ...", so I wasn't 100% sure if it was necessary for me to install OpenSSL or if that was just a suggestion for viewing certificates.

Similarly, the section on configuring LDAP.CONF gives me pause - it says I need to configure LDAP.CONF within the c:/openldap/sysconf directory, but that directory does not exist on my system. Do I need to create it? If so, what about the reference to c:\openldap\sysconf\dc.crt that also doesn't exist?
Is there something I forgot to install? I saw nothing in the Requirements section that said an installation of an OpenLDAP program was required.

**Comment by MeissnerDa** [comment] 2018-08-08 09:03
Hello @sksoftwaredev,

no it should not be necessary to install additional software. Yes you have to create those directories and files if they do not exist. 

Best regards,
meissnerDa

**Comment by sksoftwaredev** [comment] 2018-08-08 12:40
I installed OpenSSL to get the certificate, created the ldap.conf and dc.crt files but still to no avail. I'm getting the same error.

Does the fact that I'm running this on an Apache server instead of IIS have anything to do with it?

**Comment by quintingsnj** [comment] 2018-08-21 14:05
I did the following (on a linux server with Apache 2)

Copied the cert from the instructions from the above mentioned website, placed the contents  in the root of my WP site, and in root/wp-admin in a file called dc.cert. Then I created a file in the same directories called ldaprc. Made sure owner and group was my Apache user (www-data), and everything worked after that on LDAP-S.

Thanks!

**Comment by sksoftwaredev** [comment] 2018-08-21 14:14
I tried copying my dc.crt file into the wp-admin folder and making a file called ldaprc as well (giving ldaprc the same contents as ldap.conf) some time back, but that didn't change anything.

**Comment by quintingsnj** [comment] 2018-08-21 14:17
You have to also have both files in the root of the website as well.

I didn't try it with only in the wp-admin, so don't know if that is what your issue is. Also, this is the only change I made - I didn't do anything with ldap.conf.

**Comment by sksoftwaredev** [comment] 2018-08-21 14:19
As I understand it, ldap.conf is the same thing as ldaprc, only for Windows environments.

I have my dc.crt and ldap.conf files exactly where it says to place them in the documentation, but it didn't work.

**Comment by quintingsnj** [comment] 2018-08-21 14:19
I just tried with those files only in wp-admin, and confirm that it does NOT work. You HAVE to have them in the root of the website as well.  Hope that helps you.

**Comment by sksoftwaredev** [comment] 2018-08-21 14:27
I forgot to mention in my original post that I've been using Bitnami WAMP Stack Version 7.1.18-1, but I've edited that in now.

**Comment by quintingsnj** [comment] 2018-08-21 14:30
Hmmm, sorry. I'm afraid I am not going to be much more help :) Hope you figure it out.

Just out of curiosity (because I am a firewall guy...you do have ports on your firewall open to port 636 right? In my case, my web server is public, so I opened up my firewall to the public IP of my webserver and forward 636 to my DC on the inside...

Anyways, good luck with getting it working :)

**Comment by sksoftwaredev** [comment] 2018-08-21 14:35
Our LDAPS connection is working with basic Windows stuff with no issues - ldp.exe confirms that 636 is available and can be communicated through, but nothing else besides Windows wants to work with it. Not this plugin, not LDAP/AD Login by miniorange, not JMAPmyLDAP from Joomla (which is a PHP tool for debugging LDAPS/SSL), nothing.

**Comment by quintingsnj** [comment] 2018-08-21 15:00
Are all of the servers that you are trying to connect TO your AD server on the same network? I am assuming that you have checked that...because if they are not, then you would probably have a firewall between them that would need the LDAP-S port opened...

**Comment by sksoftwaredev** [comment] 2018-08-21 15:01
Everything we're using is on our local network, inside our domain.

**Comment by quintingsnj** [comment] 2018-08-21 15:02
OK, well, then that rules that out...only other thing I can think of is a local firewall on your Windows DC...other than that, I'm out of ideas :)

Just out of curiosity, can you telnet FROM your Apache box TO your DC on port 636? telnet servername 636

**Comment by sksoftwaredev** [comment] 2018-08-21 15:02
Our firewalls won't bother anything moving within the network, but do restrict things outside of it so it should not be a firewall issue.

**Comment by sksoftwaredev** [comment] 2018-08-21 15:11
Our DC isn't a Telnet server, so wouldn't that prevent it from connecting anyway?

**Comment by quintingsnj** [comment] 2018-08-21 15:21
No, telnet can be used as a way of confirming if a server is listening on a specified port...telnet just returns whatever is running on that port returns...you can use it to verify a webserver by typing telnet webserver.domain.com 80

Q

**Comment by quintingsnj** [comment] 2018-08-21 15:31
I should also point out that for some things, telnet doesn't return anything (especially in the case of SSL), but you should end up with a flashing cursor at the top left corner of your screen...if it doesn't connect at all, you will get an error.

**Comment by sksoftwaredev** [comment] 2018-08-21 15:34
The cursor doesn't flash, but after I enter telnet <domain> 636 it does bring up a solid cursor on the left, and an otherwise empty command window. So I assume it did connect.

**Comment by quintingsnj** [comment] 2018-08-21 15:36
Hmmm, mine flashes when I try that...but yeah, if no errors, I would assume it connected...at least that is verified then...not sure what the problem is with NADI then...

Oh wait, you need to enter the servername...so you are running telnet from the WEB server, and using the ip or name of the DC...

telnet dcname 636

Q

**Comment by sksoftwaredev** [comment] 2018-08-21 15:38
That's what I did - should probably have made that more clear.

**Comment by quintingsnj** [comment] 2018-08-21 15:40
OK, then you have confirmed that at least the web server can access DC on port 636...so the problem definitely lies in your WP / NADI implementation somewhere...sorry, not sure what else it could be.

Q

**Comment by sksoftwaredev** [comment] 2018-08-21 15:43
Thanks for your help!

**Comment by quintingsnj** [comment] 2018-08-21 15:52
No problem...not sure that I really helped though ;-)

**Comment by schakko** [comment] 2019-01-30 09:23
Closing this issue because such errors are environment independent.

**Closed by schakko** 2019-01-30 09:23 UTC
Labels: support case
